### ISSUE TITLE
PrintfFormat explanation

### ISSUE THREAD

**Issue by bohdanszymanik** [tamizhvendan/blog-samples#1]
Great example code but thought it might be worth providing some more explanation on the use of PrintfFormat with dynamically constructing a pathScan route - this had me scratching my head for awhile - the suave music store book doesn't explain it and the msdn docs for PrintfFormat are basically empty.

**Comment by tamizhvendan** [comment]
Sorry @bohdanszymanik I missed your comment.

Yeah, I have also faced the same problem. Just learnt enough to implement the example.
