### ISSUE TITLE
SuaveJwtSampleApplication/SuaveJwt/JwtToken.fs dependency problems

### ISSUE THREAD

**Issue by rexmondo** [tamizhvendan/blog-samples#7]
Hi, thanks so much for this book, I am considering some F# in a C# project at work and the architecture examples present here have been a big help in making this assessment for our specific requirements.

I just wanted to give you a heads up that it is not possible to run the code for the Jwt sample application picking the newest versions of all the libraries that it depends on. There appears to have been some backwards incompatible changes to `System.IdentityModel.Tokens.Jwt` assembly that prevent it.

I found that by using `open System.IdentityModel.Tokens` it was not able to find the `JwtSecurityToken` or `JwtSecurityTokenHandler` classes, and if i instead used `open System.IdentityModel.Tokens.Jwt` it could find all the constructors but would not let me use the `signingCredentials` object as written.

The solution for me was to downgrade the `System.IdentityModel.Tokens.Jwt` nuget package to its latest 4.x release (instead of newest 5.1). I can't really glean from the MSDN pages what changed, so that is the solution I am going to stick with. I just figured I would drop a note here for anyone else attempting this section.

Thanks again for your excellent work.

Ben

**Comment by tamizhvendan** [comment]
Thanks @rexmondo for the nice words and I appreciate the detailed explanation of the issue. As I am currently held up with some important works, I am not sure whether I am able to fix it right now. So, by any chance, if you found a fix for the newest version, feel free to send me a pull-request. 

Regards,
Tamizh

**Comment by rexmondo** [comment]
I'll post anything I figure out if I get a chance to look into it any more.
